version: "3.9"
services:
  web:
    build: ./typescript/simple-mercari-web
    ports:
      - "3000:3000"
    user: "trainee:mercari"
    volumes:
      - ./typescript/simple-mercari-web:/app
    environment:
      REACT_APP_API_URL: "http://localhost:9000"
    depends_on: 
       - api
  api:
    build: ./go
    ports:
      - "9000:9000"
    user: "trainee:mercari"
    volumes:
      - ./go:/app
    environment:
      FRONT_URL: "http://localhost:3000"
