FROM golang:1.21-alpine

# ダイナミックリンクでビルドするために必要なファイルをインストール
RUN apk add --no-cache gcc musl-dev

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

# イメージ内に作業ディレクトリを設定
WORKDIR /app

# 必要なファイルを/appにコピー
COPY . .

# dbディレクトリ内の複数ファイルの所有者を変更
RUN chown -R trainee:mercari db

# appディレクトリ内の複数ファイルの所有者を変更
RUN chown -R trainee:mercari app

# imagesディレクトリ内の複数ファイルの所有者を変更
RUN chown -R trainee:mercari images

# go.modファイルの所有者を変更
RUN chown trainee:mercari go.mod

USER trainee

RUN go mod download

# 各パッケージのビルドと実行
RUN go build -o ./app/constant/constant ./app/constant
RUN go build -o ./app/image/image ./app/image
RUN go build -o ./app/model/model ./app/model

# main.goを実行
CMD ["go", "run", "./app/main.go"]
