FROM node:20-alpine

RUN addgroup -S mercari && adduser -S trainee -G mercari

WORKDIR /app

COPY . .

RUN chown -R trainee:mercari /app

RUN npm ci

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

USER trainee

CMD ["npm", "start"]
